<br />
<div style="text-align: left; font-family: Arial; font-size: 13px; font-weight: 500;">

    Gentilissimo cliente, benvenuto nell'area di gestione del suo sito.

    <br />
    <br />

    Pu&ograve; effettuare la gestione del sito nelle aree elencate nei pannello a sinistra cliccando sui rispettivi pulsanti.

    <br />
    <br />

    La ringraziamo per aver scelto <a href="http://www.mbcraft.it">MBCRAFT</a>, le ricordiamo che in qualsiasi momento può contattare il nostro servizio customer care, la seguiremo passo passo nella gestione dei suoi contenuti, testi, immagini e molto altro ancora. <br />
    I nostri contatti sono :

    <br />
    <br />

    <table cellpadding="3" cellspacing="3" class="tabella_contatti_small">
        <tbody>
            <tr>
                <td>Generico</td>
                <td><a href="mailto:info@mbcraft.it">info@mbcraft.it</a></td>
            </tr>
        </tbody>
    </table>
    <br />
    Grazie per aver scelto MBCRAFT.<br />
    <br />
    -Lo Staff

</div>