<br />
<div style="text-align: left; font-family: Arial; font-size: 13px; font-weight: 500;">

    Gentilissimo cliente, benvenuto nell'area di gestione del suo sito.

    <br />
    <br />

    Pu&ograve; effettuare la gestione del sito nelle aree elencate nei pannello a sinistra cliccando sui rispettivi pulsanti.

    <br />
    <br />

    La ringraziamo per aver scelto <a href="http://www.frostlab.it">Frostlab gate</a>, le ricordiamo che in qualsiasi momento può contattare il nostro servizio customer care, la seguiremo passo passo nella gestione dei suoi contenuti, testi, immagini e molto altro ancora. <br />
    I nostri contatti sono :

    <br />
    <br />

    <table cellpadding="3" cellspacing="3" class="tabella_contatti_small">
        <tbody>
            <tr>
                <td><a href="http://it.linkedin.com/in/michelerispoli">Dr. Rispoli Michele</a></td>
                <td>Responsabile commerciale</td>
                <td><a href="mailto:michele.rispoli@frostlab.it">michele.rispoli@frostlab.it</a></td>
            </tr>
            <tr>
                <td><a href="http://it.linkedin.com/pub/marco-bagnaresi/37/92/625">Dr. Bagnaresi Marco</a></td>
                <td>Responsabile tecnico</td>
                <td><a href="mailto:marco.bagnaresi@frostlab.it">marco.bagnaresi@frostlab.it</a></td>
            </tr>
            <!--
            <tr>
                <td><a href="http://it.linkedin.com/pub/stefano-pelloni/11/23a/6aa">Pelloni Stefano</a></td>
                <td>Responsabile WEB</td>
                <td><a href="mailto:stefano.pelloni@frostlab.it">stefano.pelloni@frostlab.it</a></td>
            </tr>
            -->
            <tr>
                <td><a href="http://www.linkedin.com/company/frostlab-gate---servizi-informatici-per-le-imprese?trk=ppro_cprof">Aziendale</a></td>
                <td>Generico</td>
                <td><a href="mailto:info@frostlab.it">info@frostlab.it</a></td>
            </tr>
        </tbody>
    </table>
    <br />
    Grazie per aver scelto Frostlab Gate.<br />
    <br />
    -Lo Staff
    <table align="center" style="padding: 10px;">
        <tr valign="top">
            <td style="vertical-align:top;">
                <iframe width="200" height="165" src="http://www.youtube.com/embed/cJMSlFTLvCo" frameborder="0" allowfullscreen></iframe>
            </td>

        </tr>
    </table>

    <script type="text/javascript"
            src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
    </script>

</div>